### ISSUE TITLE
Ecuador: Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#104]
Hi,
Check please the data for Ecuador: Cumulative number of performed CV tests
Ecuador,2021-09-07,16059979,17842885,Ecuador,https://www.salud.gob.ec/actualizacion-de-casos-de-coronavirus-en-ecuador/,16059979,17842885
Looks like the data is wrong for 09/07/2021
Could you please advise?

**Comment by dsbb-finddx** [comment]
Thank you @DataOps-epam for your feedback.
@angelicambg cumulative number of tests for Ecuador on 07/09 is lower than the one in 06/09.
Can you please look into this?
![Screenshot 2021-09-07 at 13 12 47](https://user-images.githubusercontent.com/62348391/132335667-204ba410-fd5d-477c-878f-26aa7d791c48.png)

**Comment by DataOps-epam** [comment]
Looks like the data for 9/7/2021 was inserted with wrong delimiter
![image](https://user-images.githubusercontent.com/80464515/132336114-59619cf7-5da1-40fc-a1f1-728de8318856.png)

**Comment by angelicambg** [comment]
thanks @DataOps-epam
On ther [website](https://www.salud.gob.ec/actualizacion-de-casos-de-coronavirus-en-ecuador/) they have reported  1’784.2885, but it's very likely they wrote double 8 by mistake. 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/38508957/132363537-cc887e24-1d33-471d-86c9-67c0a396751a.png">

We will use 1’784.285 instead and double check tomorrow the numbers.

**Comment by DataOps-epam** [comment]
Hi, we are still getting the data point 17842885 for the 9/7/2021 and 9/8/2021 periods.

**Comment by dsbb-finddx** [comment]
@angelicambg website still shows 1’784.2885
Can we manually correct to previous correct value please?

**Comment by angelicambg** [comment]
I just added to the corrected columns the last correct value for yesterday and today. Now those changes are included in [processed/coronavirus_tests.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv).

Depending on the update later today or tomorrow I'll change the values again.

**Comment by angelicambg** [comment]
The new values published are correct.
