### ISSUE TITLE
USA: Cumulative Number Of Performed CV Tests suspicious jump

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#111]
Could you please check your time series below?
Link: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

USA: Cumulative Number Of Performed CV Tests

Data point for 09/30/2021 period  is significantly higher in compare with previous one.
Could you please advise if you know any infor regarding nature of such data change?

**Comment by dsbb-finddx** [comment]
@DataOps-epam thank you for your feedback.
We use [this](https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/testing_data/time_series_covid19_US.csv) source for testing data from the US.
The data in our time series corresponds on the "tests_combined_total" column of the above source for the date 09/30/2021 onwards.
Our time series from 2021-09-18 to 2021-09-29 does not include any values, we will investigate and use the source to add historical data.
@angelicambg can you please check on USA time series from 2021-09-18 to 2021-09-29?

**Comment by angelicambg** [comment]
The automated scraping failed between 2021-09-18 to 2021-09-29.  I just corrected manually. Therefore, when the triggered workflow ends, [coronavirus_tests.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv) should reflect the manual changes.

**Comment by dsbb-finddx** [comment]
> The automated scraping failed between 2021-09-18 to 2021-09-29. I just corrected manually. Therefore, when the triggered workflow ends, [coronavirus_tests.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv) should reflect the manual changes.

Thank you @angelicambg

**Comment by dsbb-finddx** [comment]
@DataOps-epam this is now solved!
