### ISSUE TITLE
Scraping Automatization: Concept

### ISSUE THREAD

**Issue by christophsax** [dsbbfinddx/FINDCov19TrackerData#12]
## Key features

- Stable infrastructure, green builds
- One discussion thread by day (pull request)
- All scraped data is stored permanently (relevant?)
- Manual editing one file per day (using the GitHub editor?) 
- It won't be necessary to run R scripts manually.

## Timeline

- Basic Workflow: Before X-mas (fingers crossed)
- Large parts of Selenium countries: This year (fingers crossed)

### Scraping

1. Use Selenium/Python to produce `test_selenium_DATE_TIME.json`
  (Selenium Error Messages go to same file)

2. Collect all json files, clean up, and produce `test_selenium_DATE_TIME.csv`, `test_selenium_DATE_TIME_missing.csv` with missing values and error message. Missing values are calculated as the diff from today to yesterday.

3. Use R to produce `test_pdf_DATE_TIME.csv` and `test_pdf_DATE_TIME_missing.csv`

### Combine various Scraping Outputs

4. Combine `test_pdf_DATE_TIME.csv` and `test_selenium_DATE_TIME.csv` into`test_DATE_TIME.csv`
 Combine `test_pdf_DATE_TIME_missing.csv` and `test_selenium_DATE_TIME_missing.csv` into `test_DATE_TIME_missing.csv`

### Manual Update

5. Imane to update `test_DATE_TIME_missing.csv`, with actual values. Upload triggers re-run of Step 5. Automated PR, can only be merged if file is valid and checkbox is green. Perhaps Auto-merge if green. If anything breaks, the PR stays open. Injestion errors can be fixed in due time. Master will always run. 

    **You won't have to run any R script just check countries when there are missing values or conflicting values.**

### Combine manual input with scraping and produce time series

6. Combine `test_DATE_TIME.csv` and `test_DATE_TIME_missing.csv` and produce a time series `test.csv`
 Target files: CSV with countries, tests, for each day, with new and accumulated test numbers

**Comment by pat-s** [comment]
Adding some more details: I've added a workflow DESCRIPTION to the [README](https://github.com/dsbbfinddx/FINDCov19Tracker/tree/automate) of the `automate` branch in `FINDCov19Tracker`.

This will be merged into the `master` branch soon and should describe the overall workflow.
@dsbb-finddx please have a look and open an issue if things are unclear.

PS: I will also create a pkgdown website for the package which includes HTML references for the indiviual functions of the package.
This might help getting a better overview of the package internals.

**Comment by pat-s** [comment]
## Status

- [x] Selenium: CI Workflow and daily deployment of `tests_cumulative` -> [here](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/selenium/automated/selenium)

- [x] R fetch: CI Workflow and daily deployment of `tests_cumulative` -> [here](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/selenium/automated/fetch)

- [ ] Combination of Selenium and R fetch: CI Workflow and daily deployment

- [ ] Single file with data from all dates

- [ ] Selenium: Robust Calculation of `new_tests` from yesterdays data

- [ ] R fetch: Robust Calculation of `new_tests` from yesterdays data

- [ ] Integration into existing workflow/substitution of `coronavirus_tests.csv`

**Comment by dsbb-finddx** [comment]
@pat-s @christophsax thank you for the concept summary and updates. Indeed, it is a bit hard for me to follow, I apologise. Before you progress and want to merge into the master branch changes that will impact the way that we upload data at the moment, please set up a call to explain to me the process.

**Comment by pat-s** [comment]
We won't make any changes that affect the current build process until everyone is up-to-date with the new workflow 👍

**Comment by pat-s** [comment]
Most of this is already in the respective READMEs. Closing here.
