### ISSUE TITLE
Argentina: Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#130]
Hi, we've got an extreme revision for 09/09/2021-11/11/2021 period with latest update.
Could you please advise on this. Thank you.

**Comment by angelicambg** [comment]
Hi @DataOps-epam. There was an issue with the automated scraping between 2021-09-09 and 2021-09-22, but once those values were corrected we could retrieve the right values until 2021-11-11.
