### ISSUE TITLE
Data-driven update-lag analysis

### ISSUE THREAD

**Issue by pat-s** [dsbbfinddx/FINDCov19TrackerData#15]
If a country does not update daily, `new_tests` will be 0 and the `tests_cumulative` the same as yesterday.

It might be interesting to automatically classify the countries in the final result based on this criterium.

I'd suggest adding a column "Last update" to https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/automated/merged files which contains the difference in days to the last update that we logged. 
Workflowwise we would

- group by country
- Calculate the lag for `tests_cumul`
- Extract the time difference between the two rows
- Add the info into a column

Besides being informative for us, this could also be displayed in the shiny app as a tooltip (or different).

@dsbb-finddx @christophsax @angelicambg

**Comment by dsbb-finddx** [comment]
@pat-s this is a very good proposition.
@christophsax something in those lines is already implemented here: https://github.com/dsbbfinddx/FINDCov19Tracker/blob/92179b1d5b13473466697467b69d09c1d8f96b94/R/shiny-data.R#L297
Would it be beneficial for the automatic workflow to add where @pat-s suggests?

**Comment by angelicambg** [comment]
This was implemented in [countries-last-update.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/issues/countries-last-update.csv) and the last update date is used in the shiny app
