### ISSUE TITLE
New scraping workflow questions

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#16]
- **`new_tests` are calculated from the different to the previous day:** what if a neg value is returned for the new_tests?
- Which function creates the [`processed/coronavirus_test.csv`](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/coronavirus_tests.csv) file?
- **The R package [{FindCovTracker}](https://dsbbfinddx.github.io/FINDCov19Tracker/reference/index.html), which powers most of the automated actions run via GitHub Actions, takes this data and writes [`processed/coronavirus_test.csv`](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/selenium/processed/) which is then taken as input for the final Shiny App** : what about the _corrected columns that are now found in the [`processed/coronavirus_test.csv`](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/coronavirus_tests.csv) file?

**Comment by dsbb-finddx** [comment]
**The R package [{FindCovTracker}](https://dsbbfinddx.github.io/FINDCov19Tracker/reference/index.html), which powers most of the automated actions run via GitHub Actions, takes this data and writes [`processed/coronavirus_test.csv`](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/selenium/processed/) which is then taken as input for the final Shiny App** : what about the _corrected columns that are now found in the [`processed/coronavirus_test.csv`] (https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/selenium/processed/coronavirus_test.csv) file?

**Comment by pat-s** [comment]
> new_tests are calculated from the different to the previous day: what if a neg value is returned for the new_tests?

The country is now added to the [countries which errored](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/issues/2021-01-18-countries-error.csv).

> Which function creates the processed/coronavirus_test.csv file?

IIRC from the call the question was asking where to find the new aggregated file. -> https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/countries-tests-all-dates.csv

>  what about the _corrected columns that are now found in the processed/coronavirus_test.csv file?

These columns now appear in the final file. 
If added to the manual file per day, the will populate through to the final file.

**Comment by pat-s** [comment]
@dsbb-finddx Are all questions here resolved?

**Comment by dsbb-finddx** [comment]
@pat-s I think you mean that corrected columns should be populated only for the errored countries?
I would like _corrected columns to be populated for all countries errored or not, because they are the ones used [here](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9/R/shiny-data.R#L118) to create the `data-all.csv`. 
Is there another intermediate file after `countries-tests-all-dates.csv` where the corrected columns will get populated?

**Comment by pat-s** [comment]
> I would like _corrected columns to be populated for all countries errored or not, because they are the ones used here to create the data-all.csv.

I did so [yesterday](https://github.com/dsbbfinddx/FINDCov19Tracker/commit/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9). Today I also backported this to all past dates.

https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/countries-tests-all-dates.csv should now look as wished?

> Is there another intermediate file after countries-tests-all-dates.csv where the corrected columns will get populated?

No.

**Comment by dsbb-finddx** [comment]
> https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/countries-tests-all-dates.csv should now look as wished?

Yes, but I still believe this file should be then used in `test-data.R` to create the `coronavirus_tests.csv` in the processed folder. Reason:
 - You will handle the NAs in the test-data.R
 - `coronavirus_tests.csv`will be used in the `shiny-data.R`
 - Users download `coronavirus_tests.csv` directly from processed folder, it would be good to keep it this way.

**Comment by pat-s** [comment]
> Yes, but I still believe this file should be then used in test-data.R to create the coronavirus_tests.csv in the processed folder.

Maybe we still misunderstand each other: [countries-tests-all-dates.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/countries-tests-all-dates.csv) is the new `coronavirus_tests.csv` and will replace it at some point.

Is the confusion caused by the differing name?

**Comment by dsbb-finddx** [comment]
> > Yes, but I still believe this file should be then used in test-data.R to create the coronavirus_tests.csv in the processed folder.
> 
> Maybe we still misunderstand each other: [countries-tests-all-dates.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/countries-tests-all-dates.csv) is the new `coronavirus_tests.csv` and will replace it at some point.
> 
> Is the confusion caused by the differing name?

Yes, the name is confusing, the final file should be coronavirus_tests.csv and it should be found in the processed folder, when the workflow will be implemented.

In that case and also referring to https://github.com/dsbbfinddx/FINDCov19TrackerData/issues/29, I prefer the `coronavirus_test.csv` to have already the NA values replaced. Hence the code starting [here](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9/R/test-data.R#L97) should run in the test-data.R 

I understand the concerns from a statistician point of view, hence maybe we could still keep the `countries-tests-all-dates.csv` as an intermediate file for that purpose.

**Comment by pat-s** [comment]
> Yes, the name is confusing, the final file should be coronavirus_tests.csv and it should be found in the processed folder, when the workflow will be implemented.

For now I've renamed it to `coronavirus_tests_new.csv`.
