### ISSUE TITLE
Bulgaria: Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#164]
Hi team,
Could you please check the data for Bulgaria: Cumulative number of performed CV tests
We can observe large jump (and revision) for the data from the 12/27/2021 periods.
Could you please advise the reason for this jump and that the data is correct?

**Comment by angelicambg** [comment]
Hi @DataOps-epam 
Thanks for the remark. The automated process didn't work for some time, so we are correcting the numbers. We let you know when we finish the update.

**Comment by angelicambg** [comment]
We have finished the update for Bulgaria
