### ISSUE TITLE
Peru: Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#170]
Hi,
Check please the data for Peru: Cumulative number of performed CV tests for 2/9/2022 period
We can observe an extremely large jump for the 2/9/2022 period and this data looks suspicious for us.
Could you please check the following data and advise if the data is correct? 
If the data is correct, please advise the reason for the following jump?

**Comment by dsbb-finddx** [comment]
Hello @DataOps-epam thank you for bringing this to our attention, we are correcting the dataset.
@angelicambg @seawaR scraping for Peru failed, please amend.

**Comment by DataOps-epam** [comment]
We got suspicious revisions for a lot of different countries. 
Could you please advise, your fix is still in progress?

**Comment by angelicambg** [comment]
fix with 8c4b850c6b767b0d87acfc2bf293c4f5bc6d5703

**Comment by DataOps-epam** [comment]
We still can observe the same data.
![image](https://user-images.githubusercontent.com/80464515/153491179-fda20d16-c522-4ff9-a9eb-e109c3fa8f3f.png)
