### ISSUE TITLE
Ireland: Cumulative Number Of Performed CV Tests - extreme revision

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#171]
Dear FIND, could you please check your time series "Ireland: Cumulative Number Of Performed CV Tests" here: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

We've got today an update with significant revision for 02/15/2022 period. Could you please advise on this. Thank you.
#IRL.COVID19.B@FIND

**Comment by dsbb-finddx** [comment]
@DataOps-epam we are in the process of revising also the historical data for Ireland, from 2021-12-31 to 2022-02-14.
We will update you as soon as this is complete.

**Comment by angelicambg** [comment]
The update between 2021-12-31 to 2022-02-14 is done
