### ISSUE TITLE
New Zealand Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#172]
Hi, 
Could you check the data for New Zealand Cumulative Number Of Performed CV Tests. 
We are able to validate this value with the source, but the value makes no sense. Looks like the source performed bad calculations for TOTAL on their side and recalculation shows that probable correct value for 02 March 2022 is 6748135

Could you advise if this can be fixed?
Thank you

**Comment by angelicambg** [comment]
thanks @DataOps-epam! some changes yesterday in New Zealand's Website triggered this error. We already made the correction. Once the automatic process is finished correct values will be displayed.
