### ISSUE TITLE
New Zealand scraping issue

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#173]
@angelicambg @seawaR there is an issue with New Zealand testing data, there is a huge increase.
Can you please correct? 
<img width="506" alt="59B47BBE-A874-468D-9A1F-D4471EFDB27A" src="https://user-images.githubusercontent.com/62348391/156616051-f818b284-51e7-46d6-bbf7-b370fe0c25f0.png">

**Comment by angelicambg** [comment]
I corrected 2 hours ago, and [coronavirus_tests.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/coronavirus_tests.csv) was updated
