### ISSUE TITLE
Suspicious data for New Zealand series - Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#179]
Hi Team,

We have observed that the value published for New Zealand on the file "[coronavirus_tests.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv)" for the period 03/16/2022 seems extreme in comparison with other historical values.
Could you please confirm that the value is correct and provide the reason for such a big jump?

Thank you in advance

Best regards,
Mariia

**Comment by angelicambg** [comment]
Dear @DataOps-epam,

thanks for mentioning it. Based on the [official source](https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/testing-covid-19) this is the current value. Additionally, checking previous official values (you can check them [here](https://www.stats.govt.nz/experimental/covid-19-data-portal)), all values are correct. 

<img width="1440" alt="Screenshot 2022-03-16 at 10 43 24" src="https://user-images.githubusercontent.com/38508957/158562713-f1c32a6b-7f7e-4a49-a5f0-22a8511fe8f3.png">

If the official source substitutes this value later today, we'll change it as well.

**Comment by angelicambg** [comment]
New Zealand corrected the value published on 2022-03-16, and we updated it as well.
