### ISSUE TITLE
Issue with New Zealand: Cumulative Number Of Performed CV Tests - 031820221255

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#180]
Hi Team,

Could you please check below measure as we noticed  suspicious revision for 3/16/2022 - 3/18/2022 time period(drop in cumulative series)? 

Measure: New Zealand: Cumulative Number Of Performed CV Tests

Source Link: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

Could you advise on this?

 Thank You.

**Comment by angelicambg** [comment]
Dear @DataOps-epam 

This is related to an erroneous value published on the website on 2022-03-16. However, this value was corrected. See also [issue 179](https://github.com/dsbbfinddx/FINDCov19TrackerData/issues/179)
