### ISSUE TITLE
suspicious revision Thailand - FIND

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#184]
Hi Team,

We have observed that data published for Thailand: Cumulative Number Of Performed CV Tests on the file:
https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv
looks suspicious for 04/05/2022. Could you please confirm that data for these series is correct and advise if you know the reason of such revision?

Could you please check and advise on this?

Thank you.
Regards

**Comment by benubah** [comment]
Thanks for reporting this!

Your observation is correct. Some days (beginning March 06, 2022) were missed by our automated data collection tool and therefore zero values were reported for those days.

The reason: the source actually provides daily test data, but it does not do this on a daily basis. A look at their [CSV](https://data.go.th/dataset/9f6d900f-f648-451f-8df4-89c676fce1c4/resource/0092046c-db85-4608-b519-ce8af099315e/download/thailand_covid-19_testing_data_update020465.csv) shows it was last updated on April 02, 2022 and so from this date (2022-04-02) till they provide the next set of updates, our reports will show `0` for those days and the cumulative values will remain the same for those days. Once they provide an update, our new tests and cumulative tests values will reflect the sum of the new tests from April 03, 2022 till the day of update, which would turn out to be a very large value like you have just seen.

We're working on a fix.
