### ISSUE TITLE
Huge increase in tests from St. Kitts & Nevis

### ISSUE THREAD

**Issue by mikelehen** [dsbbfinddx/FINDCov19TrackerData#185]
```
set,name,unit,time,cum_tests_orig,new_tests_orig,pop_100k,pop,new_cases_orig,new_deaths_orig,cap_cum_cases,cap_new_cases,cap_cum_deaths,cap_new_deaths,cap_cum_tests,cap_new_tests,all_cum_cases,all_new_cases,all_cum_deaths,all_new_deaths,all_cum_tests,all_new_tests,pos
country,St. Kitts & Nevis,KNA,2022-04-04,68241,200,0.53,53,0,0,104.69811320754717,0,0.8113207547169812,0,1287.566037735849,1.1320754716981132,5549,0,43,0,68241,60,0
country,St. Kitts & Nevis,KNA,2022-04-05,68241,0,0.53,53,1,0,104.71698113207547,0,0.8113207547169812,0,7081.226415094339,828.6792452830189,5550,0,43,0,375305,43920,0
country,St. Kitts & Nevis,KNA,2022-04-06,682370,614129,0.53,53,1,0,104.73584905660377,0,0.8113207547169812,0,12874.905660377359,1656.2830188679245,5551,0,43,0,682370,87783,0
```

Cumulative tests increased from 68241 to 682370 on 2022-04-06 causing huge outliers in new_tests_orig, all_new_tests, etc.

**Comment by findanna** [comment]
@mikelehen thank you for reporting this.
Currently the [source](https://covid19.gov.kn/) for St. Kitts and Nevis reports `682,370` total tests performed, but `2` is probably a typo.
Because when adding the number of positive tests (`5551`) and negative tests (`62819`) the total is `68,370`.
@angelicambg @seawaR can you please fix this?

**Comment by benubah** [comment]
I sent the [source](https://covid19.gov.kn/) an email to see if they can also correct from their end. (This data is collected by selenium)

**Comment by seawaR** [comment]
I corrected the total tests for 2022-04-06 and 2022-04-07 and will continue to correct them until the source is fixed.

**Comment by findanna** [comment]
Thank you @benubah and @seawaR

**Comment by benubah** [comment]
It worked - they have now corrected it at the source:

![image](https://user-images.githubusercontent.com/11357251/162481078-72809707-80b9-49de-995c-be4ff875b096.png)

Thanks everyone!

**Comment by mikelehen** [comment]
Awesome, thank you!
