### ISSUE TITLE
Create a dictionary for the country status 

### ISSUE THREAD

**Issue by pat-s** [dsbbfinddx/FINDCov19TrackerData#19]
in file `manual/countries-manual.csv` for every day

column: `country.status`

So that is clear what is meant with the `key`.

**Comment by pat-s** [comment]
@angelicambg Is this ticket addressed?

**Comment by angelicambg** [comment]
The dictionary is in the folder [resources/dict_status_countries.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/resources/dict_status_countries.csv)
