### ISSUE TITLE
Many countries found in jhu_data.csv but not in coronavirus_cases.csv

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#2]
I.e. South Africa, is downloaded from the jhu repository, is found in the jhu_cases.csv file but not in the processed coronavirus_cases.csv file.
This results in countries not showing up on the map etc.

**Comment by pat-s** [comment]
This is because mapping data (from `countries_codes_and_coordinates.csv`) is missing for many countries. All countries which lack mapping data are currently dropped. 

See https://github.com/dsbbfinddx/data/runs/849622535?check_suite_focus=true#step:15:16.

**Comment by dsbb-finddx** [comment]
Why, is it working though on the current map?

**Comment by pat-s** [comment]
Because that's how it was done in the code when I started:

https://github.com/dsbbfinddx/FIND_Cov_19_Tracker/blob/a721799563caa658bbcc39fb38a7381b5e63cd2e/jhu_data_full.R#L113-L117

**Comment by pat-s** [comment]
Might be solved by using the correct `countries_codes_and_coordinates.csv` file as commented in https://github.com/dsbbfinddx/data/issues/1#issuecomment-655582354.

**Comment by pat-s** [comment]
> Because that's how it was done in the code when I started:

With this I meant "before I started" 😄 

@dsbb-finddx Is this solved now after using the new coordinates file?

**Comment by dsbb-finddx** [comment]
@pat-s still no US, South Africa etc showing up on the map.

**Comment by pat-s** [comment]
In the coordinates file country names have no spaces (e.g. "SouthAfrica") whereas the JHU data includes spaces for such country names ("South Africa").

I now aligned both datasets to match so that no countries are dropped anymore.
The run at noon (in 13 minutes) should write data files without missing countries.

cc @christophsax

**Comment by pat-s** [comment]
South Africa and friends are present in the data meanwhile.
