### ISSUE TITLE
countries should be added to selenium process

### ISSUE THREAD

**Issue by angelicambg** [dsbbfinddx/FINDCov19TrackerData#22]
List of countries to include in the selenium process:

- [x] Andorra (https://www.govern.ad/covid19/en/)
- [ ] Argentina special dashboard grafana (new link dashboard: https://www.argentina.gob.ar/salud/coronavirus-COVID-19/sala-situacion)
- [x] Cambodia (new link) / update: no information about tests
- [ ] Costa Rica (xlsx: https://geovision.uned.ac.cr/oges/index.html)
- [x] Cuba (similar to Iran, Jamaica, Japan, Romania, Russia, San Marino, Spain)/ update: numbers as letters: http://www.cubadebate.cu/?s=Cuba+reporta)
- [x] Cyprus (daily number) / update: Will be included in the workflow: https://covid19.ucy.ac.cy/)
- [x] Fiji (new link, html now and not pdf anymore: http://www.health.gov.fj/covid-19-updates/)
- [x] Georgia (daily number) / update: Will be included in the workflow: https://stopcov.ge/en/
- [x] Greece (new link)
- [x] Greenland (new link)
-  Israel (daily number) / Will be included in the workflow: https://datadashboard.health.gov.il/COVID-19/general
- Japan: lag in the date they published. For now, it will be commented on in the Selenium script. But the idea is that it can be included in the workflow
- [x] Jordan (https://corona.moh.gov.jo/en)
- Kazakhstan: special dashboard saving numbers in images ( similar to Denmark, El Salavador, Guatemala, Malta, Myanmar, North Macedonia, Portugal, Saudi Arabia, Taiwan, Uruguay)
- [x] Latvia (new website: https://spkc.maps.arcgis.com/apps/opsdashboard/index.html#/4469c1fb01ed43cea6f20743ee7d5939)
- [x] Luxembourg (daily number) / update: Will be included in the workflow Will be included in the workflow: https://msan.gouvernement.lu/fr/graphiques-evolution.html
- [x] Netherlands (weekly number) / update: Will be included in the workflow: 
https://www.rivm.nl/en/novel-coronavirus-covid-19/current-information
- Paraguay _Dashboard with images_ (similar to Denmark, El Salavador, Guatemala, Malta, Myanmar, North Macedonia, Portugal, Saudi Arabia, Taiwan, Uruguay)
https://www.mspbs.gov.py/reporte-covid19.html
- [ ] Peru (xlsx or dashboard similar to Denmark, El Salavador, Guatemala, Malta, Myanmar, North Macedonia, Portugal, Saudi Arabia, Taiwan, Uruguay:
https://covid19.minsa.gob.pe/sala_situacional.asp)
- Philippines (similar to Denmark, El Salavador, Guatemala, Malta, Myanmar, North Macedonia, Portugal, Saudi Arabia, Taiwan, Uruguay) / update: Dashboard with images: https://www.doh.gov.ph/covid19tracker
- Russia: lag in the date they published. For now, it will be commented on the Selenium script. But the idea is that it can be included in the workflow: https://www.rospotrebnadzor.ru/search/index.php?tags=&q=%C8%ED%F4%EE%F0%EC%E0%F6%E8%EE%ED%ED%FB%E9+%E1%FE%EB%EB%E5%F2%E5%ED%FC+%EE+%F1%E8%F2%F3%E0%F6%E8%E8+%E8+%EF%F0%E8%ED%E8%EC%E0%E5%EC%FB%F5+%EC%E5%F0%E0%F5+%EF%EE+%ED%E5%E4%EE%EF%F3%F9%E5%ED%E8%FE+%F0%E0%F1%EF%F0%EE%F1%F2%F0%E0%ED%E5%ED%E8%FF+%E7%E0%E1%EE%EB%E5%E2%E0%ED%E8%E9%2C+%E2%FB%E7%E2%E0%ED%ED%FB%F5+%ED%EE%E2%FB%EC+%EA%EE%F0%EE%ED%E0%E2%E8%F0%F3%F1%EE%EC&where=&how=d&from=&to=
- [ x] Saint Kitts and Nevis (new link:https://covid19.gov.kn/) 
- [ ] Saudi Arabia: https://covid19.moh.gov.sa/
- Scotland (similar to Denmark, El Salavador, Guatemala, Malta, Myanmar, North Macedonia, Portugal, Saudi Arabia, Taiwan, Uruguay) / update: Dashboard with images / update: special dashboard: https://public.tableau.com/profile/phs.covid.19#!/vizhome/COVID-19DailyDashboard_15960160643010/Dailyupdate
- Sweden weekly number instead of cumulative (new link: https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/antalet-testade-for-covid-19/)
- [ ] Thailand (xlsx file new link: http://nextcloud.dmsc.moph.go.th/index.php/s/wbioWZAQfManokc)
- [x] Venezuela (similar to Iran, Jamaica, Japan, Romania, Russia, San Marino, Spain) / update: Not always number of test: https://covid19.patria.org.ve/?s=de+la+lucha+contra+la+COVID-19%3A)

**Comment by angelicambg** [comment]
@dsbb-finddx  @ImaneElIdrissi [Africa dashboard](https://africacdc.org/covid-19/) doesn't show the country names when you click on each circle. 

Using Selenium you won't get an error, but it's not possible to link countries and the number of tests.  So, it's very likely you don't get the last update because it's necessary to use another ID instead of the country name.

We fixed this using the [API behind the dashboard](https://services8.arcgis.com/vWozsma9VzGndzx7/ArcGIS/rest/services) using the layers [NEW_Dashboard](https://services8.arcgis.com/vWozsma9VzGndzx7/ArcGIS/rest/services/NEW_Dashboard/FeatureServer) to get country names and [Dashboard_1day_Sht1](https://services8.arcgis.com/vWozsma9VzGndzx7/ArcGIS/rest/services/Dashboard_1day_Sht1/FeatureServer) to get the number of tests.

Did you handle this issue differently?

**Comment by ImaneElIdrissi** [comment]
The following countries are signed as automatized but either they are not or not working:

- Cambodia: http://cdcmoh.gov.kh/
-  Cuba (similar to Iran, Jamaica, Japan, Romania, Russia, San Marino, Spain)/ update: numbers as letters: http://www.cubadebate.cu/?s=Cuba+reporta)
- Cyprus (daily number) / update: Will be included in the workflow: https://covid19.ucy.ac.cy/)
- Georgia (daily number) / update: Will be included in the workflow: https://stopcov.ge/en/
- Jordan (https://corona.moh.gov.jo/en)
- Luxembourg (daily number) / update: Will be included in the workflow Will be included in the workflow: https://msan.gouvernement.lu/fr/graphiques-evolution.html
- Netherlands (weekly number) / update: Will be included in the workflow:
https://www.rivm.nl/en/novel-coronavirus-covid-19/current-information
-  Venezuela (similar to Iran, Jamaica, Japan, Romania, Russia, San Marino, Spain) / update: Not always number of test: https://covid19.patria.org.ve/?s=de+la+lucha+contra+la+COVID-19%3A)
