### ISSUE TITLE
data_all.csv not updated since 1/14/21

### ISSUE THREAD

**Issue by janinewhite** [dsbbfinddx/FINDCov19TrackerData#23]
https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/data_all.csv has not been updated since 1/14/2021.

**Comment by pat-s** [comment]
Thanks @janinewhite. This is because no sources were added since this date.

@dsbb-finddx or @ImaneElIdrissi are responsible here - maybe they can help.

**Comment by dsbb-finddx** [comment]
Hello @janinewhite , this will be updated in due time. Thank you for your patience :)

**Comment by pat-s** [comment]
AFAICS the data has been updated again.
