### ISSUE TITLE
new_tests, cumulative_tests values not calculated in the automated/countries-tests-all-dates.csv

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#24]
There are countries that have values in the cumulative tests column, but the new tests remains 0.
Shouldn't there be a calculation at this stage for the new_tests?
Also, some countries have NA values both for cumulative and new tests. Shouldn't they have the cumulative values of the most recent date that was not empty?
Or this will be done with the integration of a next step so that the coronavirus_tests.csv is produced?

**Comment by pat-s** [comment]
The difference is calculated for all countries. 0 means that there was no change to the value logged for the previous day. 

I did not check the outcome of individual countries yet to double check if everything works as expected for each individual country. 

Feel free to have a look into the code if you have some spare time 🙂

**Comment by dsbb-finddx** [comment]
The outcome on new tests is correct :)

**Comment by pat-s** [comment]
Sounds good. Can we close this issue then?
