### ISSUE TITLE
General NA handling

### ISSUE THREAD

**Issue by pat-s** [dsbbfinddx/FINDCov19TrackerData#29]
_Originally posted by @pat-s in https://github.com/dsbbfinddx/FINDCov19TrackerData/issues/26#issuecomment-770739894_

I think we discussed this before but I can't find it anywhere. 

We do not want to show NA's in the Shiny app. Hence, for countries which reported nothing for a specific day (for any reason) we should probably report the last valid number.

@dsbb-finddx Is that correct?

**Comment by pat-s** [comment]
Maybe move to https://github.com/dsbbfinddx/FINDCov19TrackerShiny

**Comment by dsbb-finddx** [comment]
@pat-s NA handling took place in [`shiny-data.R`](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/master/R/shiny-data.R). 
We should keep all NA handling in [FINDCov19Tracker](https://github.com/dsbbfinddx/FINDCov19Tracker).
NA handling for test data should happen in [`test-data.R`](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9/R/test-data.R#L97)

**Comment by pat-s** [comment]
> NA handling took place in shiny-data.R.

Which is correct because this function runs **after** the test values have been written.

> We should keep all NA handling in FINDCov19Tracker.

I am fine with any of these as long as the shiny preprocessing happens after the value gathering step.

> NA handling for test data should happen in test-data.R

I still disagree because of https://github.com/dsbbfinddx/FINDCov19TrackerData/issues/26#issuecomment-771469017.

**Comment by angelicambg** [comment]
[coronavirus_tests.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/coronavirus_tests.csv)  doesn't have NA or negative values for the corrected columns, and this file is based on [coronavirus_tests_new.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/coronavirus_tests_new.csv). This process is handle with the function [process_test_data()](https://dsbbfinddx.github.io/FINDCov19Tracker/reference/process_test_data.html)

[coronavirus_tests_new.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/coronavirus_tests_new.csv) might contain NA or negative values when those are not fixed yet based on the [manual files uploaded ](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/processed).
