### ISSUE TITLE
 template daily csv

### ISSUE THREAD

**Issue by angelicambg** [dsbbfinddx/FINDCov19TrackerData#31]
Automatically create a template in [manual/processed](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/processed) of the daily csv file to fill the numbers. The file will have the countries with NA and countries with negative numbers, and the last column with the url.

**Comment by angelicambg** [comment]
This [commit](https://github.com/dsbbfinddx/FINDCov19Tracker/commit/ab5d17ff2df445b6467379f3709b4a1381082ae0) creates a template file in [manual/need-processing](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/need-processing). 

This template can be copy and paste in [manual/processed](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/processed), and fill tests_cumulative, or new_tests. 

If a country doesn't have a report for a particular day, then new_tests should be 0 (zero) when the file in [manual/processed](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/processed) is filled.

**Comment by pat-s** [comment]
Thanks!

The column names need some polishing I think because they still have the `country` prefix:

```r
names(countries_manual)                                                                    
[1] "country.jhu_ID"           "country.tests_cumulative" "country.new_tests"       
[4] "country.date"             "country.source"           "country.status"          
[7] "country.url" 
```

**Comment by ImaneElIdrissi** [comment]
Many thanks, the template is very user-friendly!

Quick questions: does it also include countries countries with negative values? And does it still need both cumulative and new tests cells to be filled or will at least the new tests be automatically calculated?

**Comment by angelicambg** [comment]
Yes, the template includes countries with negative values. And it calculates automatically new tests or cumulative test depending on which cell you fill the number.

I'm still testing the process but you will need to upload the same file as the template, including countries that don't update values every day. For those countries, new test should be filled with 0. 

As soon as I finish the test, I'll let you know the details.

**Comment by ImaneElIdrissi** [comment]
Thanks a lot! And regarding countries with a date shift (Jamaica, Russia, and Japan) I don't see them appearing in the manual file. If the scraping doesn't take into account the date, can you remove them from the automated countries?

**Comment by pat-s** [comment]
@angelicambg Is this done?

**Comment by angelicambg** [comment]
closed with [commit](https://github.com/dsbbfinddx/FINDCov19Tracker/commit/d763d18aff791cdc86b763e56ee41314485151d0) `test_cumulative` is set to 0 to see easily the automated countries with an error.
