### ISSUE TITLE
Add compatibility with latest dplyr version

### ISSUE THREAD

**Issue by pat-s** [dsbbfinddx/FINDCov19TrackerData#33]
_Originally posted by @dsbb-finddx in https://github.com/dsbbfinddx/FINDCov19TrackerData/issues/30#issuecomment-774035287_

Currently we use dplyr 1.0.3 due to an issue in 1.0.4.

The respective part needs to be updated and checked locally.

Assigning Christoph since he wrote this code.

**Comment by christophsax** [comment]
Don't really understand why, but purrr formula seems to work where a normal function does not:

https://github.com/dsbbfinddx/FINDCov19Tracker/commit/e085d3158ee0ffaacfaebe62dd3b867940854b5b

**Comment by pat-s** [comment]
Maybe a bug that should be reported in dplyr?

**Comment by christophsax** [comment]
https://github.com/tidyverse/dplyr/issues/5740

**Comment by pat-s** [comment]
Fixed by Christoph in https://github.com/dsbbfinddx/FINDCov19Tracker/commit/e085d3158ee0ffaacfaebe62dd3b867940854b5b.
