### ISSUE TITLE
Final file with NAs and Negative values corrected 

### ISSUE THREAD

**Issue by ImaneElIdrissi** [dsbbfinddx/FINDCov19TrackerData#34]
Is the discussed final file with deleted NAs and negative values from **coronavirus_tests_new.csv** already included in the workflow?

**Comment by angelicambg** [comment]
[coronavirus_tests.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/coronavirus_tests.csv)  doesn't have NA or negative values for the corrected columns, and this file is based on [coronavirus_tests_new.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/coronavirus_tests_new.csv).

[coronavirus_tests_new.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/coronavirus_tests_new.csv) might contain NA or negative values when those are not fixed yet based on the [manual files uploaded ](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/processed).
