### ISSUE TITLE
Thailand Testing Data

### ISSUE THREAD

**Issue by jdblant** [dsbbfinddx/FINDCov19TrackerData#39]
The average daily new tests conducted numbers in the FIND Test tracker are about 30% of that reported by the Thai MoH (http://nextcloud.dmsc.moph.go.th/index.php/s/wbioWZAQfManokc).

**Comment by ImaneElIdrissi** [comment]
Thank you for your feedback. We were indeed taking our data from the Thai dedicated [dashboard ](https://ddc.moph.go.th/viralpneumonia/eng/index.php). However it was only showing the number of "Patient Under Investigation". Thank you for having pointed at the existence of more precise data. We have now updated our data for Thailand and from now on will be using this [source](http://nextcloud.dmsc.moph.go.th/index.php/s/wbioWZAQfManokc).
