### ISSUE TITLE
Add scraping for these countries

### ISSUE THREAD

**Issue by ImaneElIdrissi** [dsbbfinddx/FINDCov19TrackerData#42]
- [ ] Afghanistan (http://covid.moph-dw.org/#/)
- [x] Argentina (special dashboard grafana: https://www.argentina.gob.ar/salud/coronavirus-COVID-19/sala-situacion)
- [x] Cambodia (http://cdcmoh.gov.kh/)
- [x] Costa Rica (xlsx: https://geovision.uned.ac.cr/oges/index.html)
- [x] Cuba (http://www.cubadebate.cu/?s=Cuba+reporta)
- [x] Indonesia (https://covid19.go.id/peta-sebaran)
- [x] Jordan (https://corona.moh.gov.jo/en)
- [x] Lithuania (https://osp.stat.gov.lt/praejusios-paros-covid-19-statistika)
- [ ] Luxembourg (https://covid19.public.lu/fr/graph.html)
- [x] Peru (https://covid19.minsa.gob.pe/sala_situacional.asp)
- [x] Saudi Arabia: https://covid19.moh.gov.sa/
- [x] Thailand  (xlsx: http://nextcloud.dmsc.moph.go.th/index.php/s/wbioWZAQfManokc)
- [ ] TheBahamas (https://www.bahamas.gov.bs/wps/portal/public/gov/government/news/All%20News%20Press%20Release)
- [x] US (https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)
- [x] Venezuela (https://covid19.patria.org.ve/?s=de+la+lucha+contra+la+COVID-19%3A)

**Comment by ImaneElIdrissi** [comment]
@angelicambg could you please check **Cambodia**, **Jordan** and **Peru** as I still see them appearing in the [_need-processing_ files](https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/manual/need-processing).
Also for **Costa Rica** wouldn't it be possible to use the _fetch_fonction_ with R?
Many thanks.

**Comment by ImaneElIdrissi** [comment]
@angelicambg could you recheck this? There is a new link for **Afghanistan**. Thank you!

**Comment by angelicambg** [comment]
- Afghanistan: [Bug with chrome](https://stackoverflow.com/questions/40514022/chrome-webdriver-produces-timeout-in-selenium), tried some solutions but unsuccessfully.
- Costa Rica: Fixed
- Cuba: Fixed
- Indonesia: Fixed
- Luxembourg: Information shows only with hover. Tried different scrapers, unsuccessfully.
- Thailand: Fixed
- The Bahamas: PDF I'll include using the fetch fucntions
- Venezuela: Several days without publishing test numbers. @ImaneElIdrissi maybe I'm looking at the wrong articles?

**Comment by dsbb-finddx** [comment]
- [ ] Brazil: http://www.giscard.com.br/coronavirus/indice-testes-realizados-covid19-brasil.php
- [ ] Ireland:https://covid-19.geohive.ie/datasets/f6d6332820ca466999dbd852f6ad4d5a_0/about (downloand csv file, contains daily number of tests under Test24 column)

**Comment by angelicambg** [comment]
This is done. At some point, we talked about letting it open in case we could change the source, but I think with the QC dashboard and the section about the sources, we could close it.

**Comment by angelicambg** [comment]
Afghanistan, Luxembourg, and The Bahamas gathered manually. URLs updated in https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/resources/countries-urls.csv
