### ISSUE TITLE
Calculations for 15-03-2021 in data_all.csv are wrong

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#47]
@angelicambg @christophsax there is an issue with calculations for countries for 15-03-21.
for regions and income all the cumulative values are 0.

for countries there are NA values in the cases columns.
Is there a problem with the jhu_cases? The file was not updated since yesterday: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/jhu_data.csv

And actions fail due to R issue: https://github.com/dsbbfinddx/FINDCov19TrackerData/actions/runs/656122823

Also, there data download in the shinyapp is not working.
Same, actions fail due to R version issue: https://github.com/dsbbfinddx/FINDCov19TrackerShiny/actions/runs/656346631

**Comment by angelicambg** [comment]
all files in processed folder were updated, and now actions are running properly.

**Comment by dsbb-finddx** [comment]
Download of selected data is still failing in the shiny app

**Comment by christophsax** [comment]
I am looking into it right now.

**Comment by christophsax** [comment]
Download is failing because of duplicate in #48. Angelica, can you look into it and fix?

**Comment by christophsax** [comment]
Seems to work again.
