### ISSUE TITLE
Czechia: Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#51]
Hi team,
Could you please check the data for the Czech Cumulative Number Of Performed CV Tests. The value for 03/22/2021 looks like a nonsense one and seems is not inline with the initial source.

https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv
https://onemocneni-aktualne.mzcr.cz/covid-19

Could you advise on this, please?
Thank You.

**Comment by ImaneElIdrissi** [comment]
Dear colleague,

Thank you for your comment. Some countries make the distinction between PCR tests and rapid antigen tests in the numbers they report. This is the case for example for Austria (https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html) and Czech Republic (https://onemocneni-aktualne.mzcr.cz/covid-19). We recently decided to show this in our tracker and we are currently working on it.

For Czech Republic, we were only reporting the number of PCRs. From the 22nd of March we started reporting the total number of tests (PCR+ rapid antigen tests) instead. Explaining the increase seen on the 22nd. The displayed value corresponds to the cumulation of both "Provedené PCR testy" and "Provedené antigenní testy". And soon we will start showing the proportions of PCRs versus rapid tests. Please note that we have the same situation for Benin, Romania, Slovakia and Slovenia. We mentioned this in the country hoovers in the table of the tracker.

Kind regards.
