### ISSUE TITLE
Urgent: corrected columns populated wrongly

### ISSUE THREAD

**Issue by ImaneElIdrissi** [dsbbfinddx/FINDCov19TrackerData#52]
@angelicambg, we noticed that some countries (ex: Greece and South Africa) didn't show a positivity rate since some time and nor daily test values while they had in [coronavirus_tests_new.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/automated/coronavirus_tests_new.csv). From [coronavirus_tests.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/data_all.csv)  @Anna then noticed that there was something wrong in the way corrected columns were populated after a negative value in original columns. It is urgent to fix this, thanks a lot.

**Comment by angelicambg** [comment]
@ImaneElIdrissi I was recalculating new_test_corrected based on tests_cumulative, and now is based on tests_cumulative_corrected. So this was corrected, and the values for Greece and South Africa are now correct.

However, it persists an issue when for many days test_cumulative is less than test_cumulative _corrected, this is the case for Mauritania. I'll look at this.
