### ISSUE TITLE
Urgent: problem with Africa CDC website

### ISSUE THREAD

**Issue by ImaneElIdrissi** [dsbbfinddx/FINDCov19TrackerData#53]
Dear @angelicambg , it seems there is something wrong in the scraping for African countries. Anna noticed that values were not updated since last week. However, from my side African countries didn't appear in the need_processing files. From a quick look to the ACDC website, it seems their interface slightly changed. Could you please have a look at this as soon as possible as it is important to have those countries updated?
Thank you so much for your help.

**Comment by dsbb-finddx** [comment]
@angelicambg could you please look into the issue Imane has reported? We need Africa data in the tracker by tomorrow because we have a presentation of the tracker.

**Comment by angelicambg** [comment]
Yes, the source for the dashboard changed, basically is a new dashboard. I'm working on it to have asap.
