### ISSUE TITLE
Fix countries for which scraping is not working anymore

### ISSUE THREAD

**Issue by ImaneElIdrissi** [dsbbfinddx/FINDCov19TrackerData#57]
Dear @angelicambg, would it be possible to have a look at all countries that are automated but stopped working? I have changed some of them. Could you check as a priority: **Croatia**, **Guatemala**, **Peru**, **Portugal**, **Romania**, **SaudiArabia**, **UnitedKingdom**, **US**.
Many thanks!

**Comment by angelicambg** [comment]
- Croatia: [Web page using Cloudflares, and most likely they changed their anti-bot protection.](https://stackoverflow.com/questions/65604551/cant-bypass-cloudflare-with-python-cloudscraper) Already tried different approaches, but unsuccessfully.
- Peru: work locally but not with Github Actions tried different approaches, but unsuccessfully. 
- Guatemala: working.
- Portugal: Fixed
- Romania: Fixed
- SaudiArabia: tried different approaches, but unsuccessfully. 
- UK: working
- US: Fixed

**Comment by ImaneElIdrissi** [comment]
Okay thank you so much @angelicambg !
