### ISSUE TITLE
option to create python files

### ISSUE THREAD

**Issue by angelicambg** [dsbbfinddx/FINDCov19TrackerData#7]
@pat-s @christophsax I pushed 2 python files. One of them is basically the python script exported from Selenium IDE. There are 2 ways to export. 

- One is to export the countries one by one, and it creates python files with the class name based on the country. 
- The second way is to export all countries at the same time, and that creates just one python file with the class name `TestDefaultSuite` and that class contains all countries.

The second option is the one you find here https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/selenium/manual/test_2_countries.py 

The first option might be better to implement further changes the user makes in Selenium, but probably with the CI might be better the second, i.e., just one big file.

Let me know what do you think.

Ps. Both options save the data extracted in one file.

**Comment by pat-s** [comment]
Having one file with all definitions is better.

The process would be to create this file once and make specific edits to write the test values to a CSV.

If a country needs an edit, this edit needs to be done manually in this file after having checked that the change works.

Did you try to run the script locally? We need to check if it runs headless or not (i.e. if a browser is spawned)

**Comment by angelicambg** [comment]
I included an option to open the browser silently. However, with that option, I got information from different countries, not the same countries I clicked on Selenium IDE.

**Comment by angelicambg** [comment]
It worked with other countries.
