### ISSUE TITLE
Suspicious data - China, Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#80]
Hi Team,

Could you please check data for China, Number Of Confirmed Cases
We can see suspicious data in 07/23/2021 as there is " China unknown" region with 37 confirmed cases only for 1 day .
Could you please advise on this?

Thank You.

 Best regards,

KATERYNA BOBRYK
Data Analyst
 
  Cell: +38063345 8621  Email: Kateryna_Bobryk@epam.com
Kyiv,  Ukraine  epam.com

**Comment by angelicambg** [comment]
Hi @DataOps-epam,

Could you tell us in which file you found the suspicious data for 07/23/2021? I check the files `coronavirus_cases.csv`, `data_all.csv`, and `jhu_data.csv` but I couldn't find easily the data for China you mentioned. Thanks!

**Comment by DataOps-epam** [comment]
I found it here: time_series_covid19_confirmed_global.csv

**Comment by angelicambg** [comment]
time_series_covid19_confirmed_global.csv is a file located in a different repo [CSSEGISandData
/
COVID-19](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series),  and sadly we don't have data for regions in China. Maybe you can check with the people involved in the repo mentioned.

**Comment by DataOps-epam** [comment]
Got it, sorry for misunderstanding. 

Have a good day.
