### ISSUE TITLE
country_info file updated names - replace in workflow

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#92]
Hello,

I am trying to consolidate more columns and update country names for the test tracker and other relevant apps that use this file.
I have uploaded this file : https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/raw/country_info_2.csv

@christophsax  @angelicambg could you please make sure you integrate this file in the workflow? It should replace the country_info.csv file. When you make sure that it can integrate you can replace the actual country_info.csv with country_info_2.csv.
Let me know if clear or would like to have a quick call.

Also, can you please check if possible to use the alpha3 codes instead of iso_alpha_2 codes, because there are frequent issues with NA (which is alpha2 code for Namibia).

**Comment by dsbb-finddx** [comment]
@benubah yes this is ok! Thank you!

**Comment by dsbb-finddx** [comment]
@benubah @angelicambg @christophsax [https://github.com/dsbbfinddx/FINDCov19TrackerData/actions/runs/1133965407](url) fail, because of new country_info file? 
[https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/processed](url) folder files were not updated since Friday 13/08

**Comment by benubah** [comment]
Sorry about this! The workflow needs this PR (https://github.com/dsbbfinddx/FINDCov19Tracker/pull/19) so that it should start working again with the new changes. But I guess @angelicambg wants to review first before merging. A review is good so as to ascertain if some existing Shiny apps would break after the changes.

**Comment by dsbb-finddx** [comment]
@benubah can we revert until @angelicambg makes the necessary checks please?
Updated data need to be added on the processed folder today.

**Comment by benubah** [comment]
Okay, the folder files have been updated now, please review: https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/processed

**Comment by angelicambg** [comment]
The process is running without errors. Thanks @benubah.

I'll merge the update for the manual files and check the errors.

**Comment by dsbb-finddx** [comment]
@benubah @angelicambg thank you very much!

**Comment by benubah** [comment]
Thanks! Test-tracker and CountryMatrix shiny apps have been updated to work with this improvement.
