### ISSUE TITLE
invalid isocodes in `data_all.csv`

### ISSUE THREAD

**Issue by christophsax** [dsbbfinddx/FINDCov19TrackerData#99]
There are some invalid isocodes in `data_all.csv`. Can we fix or remove them?

``` r
library(tidyverse)
data_all <- readr::read_csv("https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/data_all.csv")

country_codes <- 
  data_all |>
  filter(set == "country") |>
  pull(unit) |>
  unique()

setdiff(country_codes, countrycode::codelist$iso3c)
#> [1] "CF" "DO" "KR" "LC" "XK" "ZA"
```

<sup>Created on 2021-08-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dsbb-finddx** [comment]
@christophsax @angelicambg is this fixed please?

**Comment by angelicambg** [comment]
Fixed with https://github.com/dsbbfinddx/FINDCov19Tracker/commit/4bb267333c1c11760bde4e3025cbd33000c471b7
